---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyfin
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: jellyfin
      version: 20.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${JELLYFIN_IP}

    persistence:
      anime:
        enabled: true
        existingClaim: media-anime-nfs-pvc
        mountPath: "/media/anime"
      movies:
        enabled: true
        existingClaim: media-movies-nfs-pvc
        mountPath: "/media/movies"
      music:
        enabled: true
        existingClaim: media-music-nfs-pvc
        mountPath: "/media/music"
      tvshows:
        enabled: true
        existingClaim: media-tvshows-nfs-pvc
        mountPath: "/media/tvshows"