apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:8dzaEswc8pEtMZlkpxwgDGUMo8clHV0VAIckMRiIIlo/RWz4yI077eapHHsOnyoLFs12Dzwpy71hDuDXdqoBvcRJzlrB3J6LNZZgQ77QfWi2pQqNQXL6bxufLOGbZTlerTVwbTc/KBX6s6n+b+4cchZjd3EoBi7UN0wU9qky1emo+G+AdVi8VotKWyEW2D+DUhHb62xOvAehIRhZVuuVKi1YwTrd7yYXksfEnct22dRR9AIB7dYUSnbO8MWovTTvW82xjisnxTy+d5mRTD6zvei97FbZe6BB+3NCB/1/pXMWUvOKeuKv8FkoH/4rvz12wXYZDNQ8C1KDzmYUvn1VeeFkMJJjBa1UAx4cdRYEjcedSQ8ZkLQTCBnkwNu7mCTd,iv:jhCgR521wAPVnlyn9kEwdL5Z8DMgwRsTZa5c9AMYlnI=,tag:ngwMWwXbJP8521J/N2n0JA==,type:str]
    identity.pub: ENC[AES256_GCM,data:7Q3xWLCV0PSdYabyGGqLb9e/pr+zBrCxRfupcMv6y69ViTCsW/n5msTNDPah1Bs9WZXTsqLTMknrVrjZJY0rvUhuaybHDmhYo7M4Dqnv2KDrfFgfnfWIr87Ms3bSz0R/kskYYziXx+kfLh8MPlu1G8Tki4B5L7EWv9+A8oY32U575jH7OeFtCVX7dASUPZECxPUC+k3xYKKP8Q5EinU2RQBTkZU30PyZRtd7BYH7iArxy3mKriOC4FrxEuwSaT6SkgFqsSJjX8rOgVC+tQ==,iv:ewV5Y21nHlxw+8zQ0jU5yHXzDp4FxteSkQL+BCBLds8=,tag:i/XHZVnCTjD69nn8Ajz9Dw==,type:str]
    known_hosts: ENC[AES256_GCM,data:CiFvIQZ79piTjLfwU+EqGHi/hT2uYjbYr5JP6K5oimwTZaXIOup2YtybZwxD2QSOAp8HLJJm6WZnCI3MH05dkEFcgmsurYnIo52B94+13lhj0ebRd7Sse9dRVGxn4WioXNSxdEA0QrFOwscH8+HP2dcNvKhB9SU75KFg5agToR6TU/vTEXumPGx/l9QXwRhZF2imgnFF4Aj46E3FQmIEj/94d59S4a/Mwdf9,iv:FgHFDZDp0FG1+rrfbYhjXX6h5QRyfuuHoqmy46cOnuA=,tag:E8hkBUTSwe8nC9HWzObn6A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1up8qvftsrger60d6gqfgxnsc4c5zm00z5z6rw4rmzyls3nee6c0sp7llcm
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN2NVcVhEVHY5c2h3MTls
            ZWk3eTdwbWI1Szk1ZWdpdGVVQmVMRktyTlhZCkw4TzBzTCtkWUI5QnJhZXByaG9v
            enhDUStCNTFkcVo0ZDcrTW5zaVQ1RGsKLS0tIGpXMURwZmFZNlRncmF1YUgrVitK
            WWdyaEo2VjQ2SVQ3K0lZZWxjMW1lR3cKJ2iJ2TSxgqV235icL+wCAVUyyOSOcGml
            m9e/t6W9wE/NcTreHl84JmSsC51wIAk3IGftuZudVEt6ubabpq4TfQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-12T01:37:58Z"
    mac: ENC[AES256_GCM,data:1/UhSR2U/CeStQWN5cY/Xjsc2396l+umT5nWmTJQV9Eh3Mz/oNgs4zYZ6j2uAA61yOqncN0+48vU1ITlepqJkhtOFeAYqYXhubi4sYGEPAgz9HW3C8uIgFc0x3QCyG5s29NIy3HoFe05k/BWVVzBZtb15WNuzkKqNa1HcHKl83A=,iv:eiwRtW8PKGO27yGoMVJOfgVYymAAFUUnfsKRo3gLcWI=,tag:OTD06KJe44nj0zfN++EX2A==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
